name: Build 64Bit

on: [push, pull_request]

jobs:

  MIN-GW:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v2
    - name: Create Compile Folder
      run: |
        mkdir ./compile
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-g++
    - name: Check version
      run: |
        gcc --version
    - name: Setting Date Variable
      id: date
      run: echo "today=$(date +'%d%m%y-%H%M%S')" >> $GITHUB_ENV
    - name: Build main.cpp
      run: |
        g++ -Wall -Wextra -o ./compile/result_${{ env.today }} ./src/main.cpp -std=c++98 -static
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2.3.1
      with:
        name: RentalMobil_${{ env.today }}
        path: ./compile/
        retention-days: 2
