name: Build 64Bit
on: [push, pull_request]

jobs:
  MIN-GW:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Compile Folder
      run: |
        mkdir ./compile

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc

    - name: Add MinGW to PATH
      run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Check version
      run: |
        gcc --version

    - name: Setting Date Variable
      id: date
      run: echo "today=$((Get-Date).ToString('ddMMyy-HHmmss'))" >> $env:GITHUB_ENV

    - name: Build main.cpp
      run: |
        g++ -Wall -Wextra -o ./compile/result_${{ env.today }} ./src/main.cpp -std=c++98 -static

    - name: Upload Artifact 
      uses: actions/upload-artifact@v3
      with:
        name: RentalMobil_${{ env.today }}
        path: ./compile/
        retention-days: 30
